[custom]
;重要！每个组名的空格后面都添加了一个隐藏字符 \u200d 用于防止与节点重名，改名需谨慎

custom_proxy_group=✈ 默认代理`select`[]🔄 按延迟自动选择`[]🇺🇸 SS_美国_CN2_GT`[]🇺🇸 Vmess_美国_CN2_GIA`[]🇯🇵 Vmess_日本_POP`[]🇳🇱 Vmess_荷兰_POP_CN2_GIA`[]📥 1/10流量_下载专线

custom_proxy_group=🐟 漏网之鱼`select`[]✈ 默认代理`[]🇺🇸 SS_美国_CN2_GT`[]🇺🇸 Vmess_美国_CN2_GIA`[]🇯🇵 Vmess_日本_POP`[]🇳🇱 Vmess_荷兰_POP_CN2_GIA`[]DIRECT

custom_proxy_group=🇺🇸 SS_美国_CN2_GT`url-test`(?=.*(S1|S2)).*$`https://i.ytimg.com/generate_204`15,,100

custom_proxy_group=🇺🇸 Vmess_美国_CN2_GIA`url-test`(?=.*(S3)).*$`https://i.ytimg.com/generate_204`15,,100

custom_proxy_group=🇯🇵 Vmess_日本_POP`url-test`(?=.*(S4)).*$`https://i.ytimg.com/generate_204`15,,100

custom_proxy_group=🇳🇱 Vmess_荷兰_POP_CN2_GIA`url-test`(?=.*(S5)).*$`https://i.ytimg.com/generate_204`15,,100

custom_proxy_group=📥 1/10流量_下载专线`url-test`(?=.*(下载专线)).*$`https://i.ytimg.com/generate_204`15,,100

custom_proxy_group=🔄 按延迟自动选择`url-test`^((?!(DIRECT|下载专线)).)*$`https://i.ytimg.com/generate_204`15,,300

enable_rule_generator=false
overwrite_original_rules=true

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/ChinaOnly.list
ruleset=DIRECT,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/UnBan1.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/BanProgramAD1.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/GoogleCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=✈ 默认代理,[]FINAL
