[custom]
;重要！每个组名的空格后面都添加了一个隐藏字符 \u200d 用于防止与节点重名，改名需谨慎

custom_proxy_group=✈️ ‍起飞`select`[]⚡ ‍低延迟`[]👆🏻 ‍指定`[]🇭🇰 ‍香港`[]🇹🇼 ‍台湾`[]🇨🇳 ‍中国`[]🇸🇬 ‍新加坡`[]🇯🇵 ‍日本`[]🇺🇸 ‍美国`[]🎏 ‍其他`[]👆🏻🇭🇰 ‍香港`[]👆🏻🇹🇼 ‍台湾`[]👆🏻🇨🇳 ‍中国`[]👆🏻🇸🇬 ‍新加坡`[]👆🏻🇯🇵 ‍日本`[]👆🏻🇺🇸 ‍美国`[]👆🏻🎏 ‍其他`[]DIRECT`[]REJECT

custom_proxy_group=⚡ ‍低延迟`url-test`^`https://i.ytimg.com/generate_204`30,,100
custom_proxy_group=👆🏻 ‍指定`select`^

custom_proxy_group=🛩️ ‍墙内`select`[]DIRECT`[]REJECT`[]✈️ ‍起飞
custom_proxy_group=💩 ‍广告`select`[]REJECT`[]🛩️ ‍墙内`[]✈️ ‍起飞

custom_proxy_group=📺 ‍B站`select`[]🛩️ ‍墙内`[]🇭🇰 ‍香港`[]🇹🇼 ‍台湾`[]🇨🇳 ‍中国`[]✈️ ‍起飞`[]👆🏻🇭🇰 ‍香港`[]👆🏻🇹🇼 ‍台湾`[]👆🏻🇨🇳 ‍中国`[]👆🏻 ‍指定
custom_proxy_group=🤖 ‍AI`select`[]🇺🇸 ‍美国`[]🇹🇼 ‍台湾`[]🇸🇬 ‍新加坡`[]🇯🇵 ‍日本`[]🎏 ‍其他`[]✈️ ‍起飞`[]👆🏻🇺🇸 ‍美国`[]👆🏻🇹🇼 ‍台湾`[]👆🏻🇸🇬 ‍新加坡`[]👆🏻🇯🇵 ‍日本`[]👆🏻🎏 ‍其他`[]👆🏻 ‍指定`[]🛩️ ‍墙内
custom_proxy_group=🌐 ‍未知站点`select`[]✈️ ‍起飞`[]🛩️ ‍墙内`[]💩 ‍广告

custom_proxy_group=🇭🇰 ‍香港`url-test`🇭🇰(?!.*(?!🇨🇳)[🇦-🇿]{2})`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇹🇼 ‍台湾`url-test`🇹🇼(?!.*(?!🇨🇳)[🇦-🇿]{2})`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇨🇳 ‍中国`url-test`(🇭🇰|🇹🇼|🇨🇳|🇲🇴)(?!.*[🇦-🇿]{2})`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇸🇬 ‍新加坡`url-test`🇸🇬(?!.*[🇦-🇿]{2})`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇯🇵 ‍日本`url-test`🇯🇵(?!.*[🇦-🇿]{2})`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇺🇸 ‍美国`url-test`(🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2})`https://i.ytimg.com/generate_204`15,,300
custom_proxy_group=🎏 ‍其他`url-test`^(?!.*(🇨🇳|🇭🇰|🇲🇴|🇹🇼|🇸🇬|🇯🇵|🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2}))`https://i.ytimg.com/generate_204`30,,100

custom_proxy_group=👆🏻🇭🇰 ‍香港`select`🇭🇰(?!.*(?!🇨🇳)[🇦-🇿]{2})
custom_proxy_group=👆🏻🇹🇼 ‍台湾`select`🇹🇼(?!.*(?!🇨🇳)[🇦-🇿]{2})
custom_proxy_group=👆🏻🇨🇳 ‍中国`select`(🇭🇰|🇹🇼|🇨🇳|🇲🇴)(?!.*[🇦-🇿]{2})
custom_proxy_group=👆🏻🇸🇬 ‍新加坡`select`🇸🇬(?!.*[🇦-🇿]{2})
custom_proxy_group=👆🏻🇯🇵 ‍日本`select`🇯🇵(?!.*[🇦-🇿]{2})
custom_proxy_group=👆🏻🇺🇸 ‍美国`select`(🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2})
custom_proxy_group=👆🏻🎏 ‍其他`select`^(?!.*(🇨🇳|🇭🇰|🇲🇴|🇹🇼|🇸🇬|🇯🇵|🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2}))

enable_rule_generator=true
overwrite_original_rules=true

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/ChinaOnly.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/UnBan1.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=💩 ‍广告,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/BanProgramAD1.list
ruleset=💩 ‍广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=💩 ‍广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/GoogleCN.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=📺 ‍B站,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 ‍B站,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🤖 ‍AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=✈️ ‍起飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🛩️ ‍墙内,[]GEOIP,CN,no-resolve
ruleset=🌐 ‍未知站点,[]FINAL
