[custom]

;自用代理组
custom_proxy_group=✈ 默认代理`select`[]🔄 按延迟自动选择`[]🇺🇸 SS_美国_CN2_GT`[]🇺🇸 Vmess_美国_CN2_GIA`[]🇯🇵 Vmess_日本_POP`[]🇳🇱 Vmess_荷兰_POP_CN2_GIA`[]📥 1/10流量_下载专线
custom_proxy_group=🐟 漏网之鱼`select`[]✈ 默认代理`[]🇺🇸 SS_美国_CN2_GT`[]🇺🇸 Vmess_美国_CN2_GIA`[]🇯🇵 Vmess_日本_POP`[]🇳🇱 Vmess_荷兰_POP_CN2_GIA`[]DIRECT
custom_proxy_group=🇺🇸 SS_美国_CN2_GT`url-test`(S1|S2)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇺🇸 Vmess_美国_CN2_GIA`url-test`(S3)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇯🇵 Vmess_日本_POP`url-test`(S4)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇳🇱 Vmess_荷兰_POP_CN2_GIA`url-test`(S5)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=📥 1/10流量_下载专线`url-test`(下载)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🔄 按延迟自动选择`url-test`^(DIRECT|下载专线)`https://i.ytimg.com/generate_204`15,,300

;自定义规则集的选项
enable_rule_generator=true
overwrite_original_rules=false

;规则集
;20230416
;自用
ruleset=DIRECT,https://raw.githubusercontent.com/shenleihaha/clash/refs/heads/master/sll_DIRECT.list

ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/zsokami/ACL4SSR/main/ChinaOnly.list

ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list

ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list


ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list
ruleset=✈ 默认代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list

ruleset==✈ 默认代理,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
