[custom]

custom_proxy_group=✈ 默认代理`select`[]🔄 按延迟自动选择`[]🇺🇸 SS_美国_CN2_GT`[]🇺🇸 Vmess_美国_CN2_GIA`[]🇯🇵 Vmess_日本_POP`[]🇳🇱 Vmess_荷兰_POP_CN2_GIA`[]📥 1/10流量_下载专线
custom_proxy_group=🐟 漏网之鱼`select`[]✈ 默认代理`[]🇺🇸 SS_美国_CN2_GT`[]🇺🇸 Vmess_美国_CN2_GIA`[]🇯🇵 Vmess_日本_POP`[]🇳🇱 Vmess_荷兰_POP_CN2_GIA`[]DIRECT
custom_proxy_group=🇺🇸 SS_美国_CN2_GT`url-test`(S1|S2)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇺🇸 Vmess_美国_CN2_GIA`url-test`(S3)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇯🇵 Vmess_日本_POP`url-test`(S4)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🇳🇱 Vmess_荷兰_POP_CN2_GIA`url-test`(S5)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=📥 1/10流量_下载专线`url-test`(下载)`https://i.ytimg.com/generate_204`15,,100
custom_proxy_group=🔄 按延迟自动选择`url-test`^(DIRECT|下载专线)`https://i.ytimg.com/generate_204`15,,300

;Options for custom rulesets
enable_rule_generator=false
overwrite_original_rules=true

rules:
  - RULE-SET,private_ip,DIRECT,no-resolve
  - RULE-SET,private_domain,DIRECT
  - DOMAIN-SUFFIX,dababa.host,DIRECT
  - DOMAIN-SUFFIX,shenleihaha.top,DIRECT
  - DOMAIN-SUFFIX,masuit.net,DIRECT
  - DOMAIN-SUFFIX,synology.com,DIRECT
  - DOMAIN-SUFFIX,maxthon.com,DIRECT
  - DOMAIN-SUFFIX,samsung.com,DIRECT
  - DOMAIN-SUFFIX,qichiyu.com,✈ 默认代理
  - RULE-SET,proxylite,✈ 默认代理
  - RULE-SET,ai,✈ 默认代理
  - RULE-SET,github_domain,✈ 默认代理
  - RULE-SET,speedtest_domain,✈ 默认代理
  - RULE-SET,youtube_domain,✈ 默认代理
  - RULE-SET,onedrive_domain,✈ 默认代理
  - RULE-SET,microsoft_domain,✈ 默认代理
  - RULE-SET,tiktok_domain,✈ 默认代理
  - RULE-SET,paypal_domain,✈ 默认代理
  - RULE-SET,google_ip,✈ 默认代理
  - RULE-SET,google_domain,✈ 默认代理
  - RULE-SET,apple_ip,DIRECT
  - RULE-SET,apple_domain,DIRECT
  - RULE-SET,telegram_ip,✈ 默认代理
  - RULE-SET,telegram_domain,✈ 默认代理
  - RULE-SET,netflix_ip,✈ 默认代理
  - RULE-SET,netflix_domain,✈ 默认代理
  - RULE-SET,twitter_ip,✈ 默认代理
  - RULE-SET,twitter_domain,✈ 默认代理
  - RULE-SET,x_domain,✈ 默认代理
  - RULE-SET,geolocation-!cn,✈ 默认代理
  - RULE-SET,cn_ip,DIRECT
  - RULE-SET,cn_domain,DIRECT
  - MATCH,🐟 漏网之鱼


rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  tracker_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tracker.mrs"}
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/proxy.mrs"}
  ai: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  twitter_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs"}
  twitter_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs"}
  x_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
